APP_PLATFORM := android-10
APP_STL := gnustl_static

APP_CFLAGS    := -DANDROID
APP_CFLAGS    += -DHAVE_STDBOOL_H
APP_CFLAGS    += -DNEED_XPARSEGEOMETRY_IMPL
APP_CFLAGS    += -DHAVE_XPARSEGEOMETRY
APP_CFLAGS    += -DEGL_VERSION_1_0
APP_CFLAGS    += -D GL_GLEXT_PROTOTYPES


APP_CFLAGS    += -DVERSION_MAJOR=3
APP_CFLAGS    += -DVERSION_MINOR=0
APP_CFLAGS    += -DVERSION_PATCH=0