.\" Process this file with
.\" groff -man -Tascii opusrtp.1
.\"
.TH opusrtp 1 2012-08-31 "Xiph.Org Foundation" "opus-tools"

.SH NAME
opusrtp \- encapsulate Opus audio in RTP

.SH SYNOPSIS
.B opusrtp
[
.B -hV
]
[
.B --sniff
]
.B file.opus
[
.B file2.opus ...
]

.SH DESCRIPTION

.B opusrtp
Demonstration tool for sending and receiving Opus audio data in RTP,
used for interactive applications on the internet.

By default, Opus audio from each given file is sent as an RTP stream.

.SH "OPTIONS"
.IP "-h, --help"
Print help message
.IP "-V, --version"
Display version information
.IP "--quiet"
Suppresses program output
.IP "--sniff"
Sniff the network for active RTP sessions and save them to .opus
files. This can be useful for debugging other Opus RTP implementations.
For this function to work, the program must be run with superuser
privileges.

.SH AUTHORS
.br
Ralph Giles <giles@thaumas.net>

.SH BUGS

Only the sniff mode is implemented; the tool should do normal unicast
and multicast send/receive.

The sniff mode should allow specifying device/host/port/payload type
to limit capture. All that is hard-coded.

.SH SEE ALSO
.BR opusdec (1),
.BR opusenc (1),
.BR opusinfo (1)
