DECLARE LIBRARY
SUB glAccum(BYVAL op AS _UNSIGNED LONG,BYVAL value AS SINGLE)
SUB glAlphaFunc(BYVAL func AS _UNSIGNED LONG,BYVAL ref AS SINGLE)
FUNCTION glAreTexturesResident~%%(BYVAL n AS LONG,textures AS _UNSIGNED LONG,residences AS _UNSIGNED _BYTE)
SUB glArrayElement(BYVAL i AS LONG)
SUB glBegin(BYVAL mode AS _UNSIGNED LONG)
SUB glBindTexture(BYVAL target AS _UNSIGNED LONG,BYVAL texture AS _UNSIGNED LONG)
SUB glBitmap(BYVAL width AS LONG,BYVAL height AS LONG,BYVAL xorig AS SINGLE,BYVAL yorig AS SINGLE,BYVAL xmove AS SINGLE,BYVAL ymove AS SINGLE,bitmap AS _UNSIGNED _BYTE)
SUB glBlendFunc(BYVAL sfactor AS _UNSIGNED LONG,BYVAL dfactor AS _UNSIGNED LONG)
SUB glCallList(BYVAL list AS _UNSIGNED LONG)
SUB glCallLists(BYVAL n AS LONG,BYVAL type AS _UNSIGNED LONG,lists AS _OFFSET)
SUB glClear(BYVAL mask AS _UNSIGNED LONG)
SUB glClearAccum(BYVAL red AS SINGLE,BYVAL green AS SINGLE,BYVAL blue AS SINGLE,BYVAL alpha AS SINGLE)
SUB glClearColor(BYVAL red AS SINGLE,BYVAL green AS SINGLE,BYVAL blue AS SINGLE,BYVAL alpha AS SINGLE)
SUB glClearDepth(BYVAL depth AS DOUBLE)
SUB glClearIndex(BYVAL c AS SINGLE)
SUB glClearStencil(BYVAL s AS LONG)
SUB glClipPlane(BYVAL plane AS _UNSIGNED LONG,equation AS DOUBLE)
SUB glColor3b(BYVAL red AS _BYTE,BYVAL green AS _BYTE,BYVAL blue AS _BYTE)
SUB glColor3bv(v AS _BYTE)
SUB glColor3d(BYVAL red AS DOUBLE,BYVAL green AS DOUBLE,BYVAL blue AS DOUBLE)
SUB glColor3dv(v AS DOUBLE)
SUB glColor3f(BYVAL red AS SINGLE,BYVAL green AS SINGLE,BYVAL blue AS SINGLE)
SUB glColor3fv(v AS SINGLE)
SUB glColor3i(BYVAL red AS LONG,BYVAL green AS LONG,BYVAL blue AS LONG)
SUB glColor3iv(v AS LONG)
SUB glColor3s(BYVAL red AS INTEGER,BYVAL green AS INTEGER,BYVAL blue AS INTEGER)
SUB glColor3sv(v AS INTEGER)
SUB glColor3ub(BYVAL red AS _UNSIGNED _BYTE,BYVAL green AS _UNSIGNED _BYTE,BYVAL blue AS _UNSIGNED _BYTE)
SUB glColor3ubv(v AS _UNSIGNED _BYTE)
SUB glColor3ui(BYVAL red AS _UNSIGNED LONG,BYVAL green AS _UNSIGNED LONG,BYVAL blue AS _UNSIGNED LONG)
SUB glColor3uiv(v AS _UNSIGNED LONG)
SUB glColor3us(BYVAL red AS _UNSIGNED INTEGER,BYVAL green AS _UNSIGNED INTEGER,BYVAL blue AS _UNSIGNED INTEGER)
SUB glColor3usv(v AS _UNSIGNED INTEGER)
SUB glColor4b(BYVAL red AS _BYTE,BYVAL green AS _BYTE,BYVAL blue AS _BYTE,BYVAL alpha AS _BYTE)
SUB glColor4bv(v AS _BYTE)
SUB glColor4d(BYVAL red AS DOUBLE,BYVAL green AS DOUBLE,BYVAL blue AS DOUBLE,BYVAL alpha AS DOUBLE)
SUB glColor4dv(v AS DOUBLE)
SUB glColor4f(BYVAL red AS SINGLE,BYVAL green AS SINGLE,BYVAL blue AS SINGLE,BYVAL alpha AS SINGLE)
SUB glColor4fv(v AS SINGLE)
SUB glColor4i(BYVAL red AS LONG,BYVAL green AS LONG,BYVAL blue AS LONG,BYVAL alpha AS LONG)
SUB glColor4iv(v AS LONG)
SUB glColor4s(BYVAL red AS INTEGER,BYVAL green AS INTEGER,BYVAL blue AS INTEGER,BYVAL alpha AS INTEGER)
SUB glColor4sv(v AS INTEGER)
SUB glColor4ub(BYVAL red AS _UNSIGNED _BYTE,BYVAL green AS _UNSIGNED _BYTE,BYVAL blue AS _UNSIGNED _BYTE,BYVAL alpha AS _UNSIGNED _BYTE)
SUB glColor4ubv(v AS _UNSIGNED _BYTE)
SUB glColor4ui(BYVAL red AS _UNSIGNED LONG,BYVAL green AS _UNSIGNED LONG,BYVAL blue AS _UNSIGNED LONG,BYVAL alpha AS _UNSIGNED LONG)
SUB glColor4uiv(v AS _UNSIGNED LONG)
SUB glColor4us(BYVAL red AS _UNSIGNED INTEGER,BYVAL green AS _UNSIGNED INTEGER,BYVAL blue AS _UNSIGNED INTEGER,BYVAL alpha AS _UNSIGNED INTEGER)
SUB glColor4usv(v AS _UNSIGNED INTEGER)
SUB glColorMask(BYVAL red AS _UNSIGNED _BYTE,BYVAL green AS _UNSIGNED _BYTE,BYVAL blue AS _UNSIGNED _BYTE,BYVAL alpha AS _UNSIGNED _BYTE)
SUB glColorMaterial(BYVAL face AS _UNSIGNED LONG,BYVAL mode AS _UNSIGNED LONG)
SUB glColorPointer(BYVAL size AS LONG,BYVAL type AS _UNSIGNED LONG,BYVAL stride AS LONG,pointer AS _OFFSET)
SUB glCopyPixels(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG,BYVAL height AS LONG,BYVAL type AS _UNSIGNED LONG)
SUB glCopyTexImage1D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL internalFormat AS _UNSIGNED LONG,BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG,BYVAL border AS LONG)
SUB glCopyTexImage2D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL internalFormat AS _UNSIGNED LONG,BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG,BYVAL height AS LONG,BYVAL border AS LONG)
SUB glCopyTexSubImage1D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL xoffset AS LONG,BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG)
SUB glCopyTexSubImage2D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL xoffset AS LONG,BYVAL yoffset AS LONG,BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG,BYVAL height AS LONG)
SUB glCullFace(BYVAL mode AS _UNSIGNED LONG)
SUB glDeleteLists(BYVAL list AS _UNSIGNED LONG,BYVAL range AS LONG)
SUB glDeleteTextures(BYVAL n AS LONG,textures AS _UNSIGNED LONG)
SUB glDepthFunc(BYVAL func AS _UNSIGNED LONG)
SUB glDepthMask(BYVAL flag AS _UNSIGNED _BYTE)
SUB glDepthRange(BYVAL zNear AS DOUBLE,BYVAL zFar AS DOUBLE)
SUB glDisable(BYVAL cap AS _UNSIGNED LONG)
SUB glDisableClientState(BYVAL array AS _UNSIGNED LONG)
SUB glDrawArrays(BYVAL mode AS _UNSIGNED LONG,BYVAL first AS LONG,BYVAL count AS LONG)
SUB glDrawBuffer(BYVAL mode AS _UNSIGNED LONG)
SUB glDrawElements(BYVAL mode AS _UNSIGNED LONG,BYVAL count AS LONG,BYVAL type AS _UNSIGNED LONG,indices AS _OFFSET)
SUB glDrawPixels(BYVAL width AS LONG,BYVAL height AS LONG,BYVAL format AS _UNSIGNED LONG,BYVAL type AS _UNSIGNED LONG,pixels AS _OFFSET)
SUB glEdgeFlag(BYVAL flag AS _UNSIGNED _BYTE)
SUB glEdgeFlagPointer(BYVAL stride AS LONG,pointer AS _OFFSET)
SUB glEdgeFlagv(flag AS _UNSIGNED _BYTE)
SUB glEnable(BYVAL cap AS _UNSIGNED LONG)
SUB glEnableClientState(BYVAL array AS _UNSIGNED LONG)
SUB glEnd()
SUB glEndList()
SUB glEvalCoord1d(BYVAL u AS DOUBLE)
SUB glEvalCoord1dv(u AS DOUBLE)
SUB glEvalCoord1f(BYVAL u AS SINGLE)
SUB glEvalCoord1fv(u AS SINGLE)
SUB glEvalCoord2d(BYVAL u AS DOUBLE,BYVAL v AS DOUBLE)
SUB glEvalCoord2dv(u AS DOUBLE)
SUB glEvalCoord2f(BYVAL u AS SINGLE,BYVAL v AS SINGLE)
SUB glEvalCoord2fv(u AS SINGLE)
SUB glEvalMesh1(BYVAL mode AS _UNSIGNED LONG,BYVAL i1 AS LONG,BYVAL i2 AS LONG)
SUB glEvalMesh2(BYVAL mode AS _UNSIGNED LONG,BYVAL i1 AS LONG,BYVAL i2 AS LONG,BYVAL j1 AS LONG,BYVAL j2 AS LONG)
SUB glEvalPoint1(BYVAL i AS LONG)
SUB glEvalPoint2(BYVAL i AS LONG,BYVAL j AS LONG)
SUB glFeedbackBuffer(BYVAL size AS LONG,BYVAL type AS _UNSIGNED LONG,buffer AS SINGLE)
SUB glFinish()
SUB glFlush()
SUB glFogf(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glFogfv(BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glFogi(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glFogiv(BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glFrontFace(BYVAL mode AS _UNSIGNED LONG)
SUB glFrustum(BYVAL left AS DOUBLE,BYVAL right AS DOUBLE,BYVAL bottom AS DOUBLE,BYVAL top AS DOUBLE,BYVAL zNear AS DOUBLE,BYVAL zFar AS DOUBLE)
FUNCTION glGenLists~&(BYVAL range AS LONG)
SUB glGenTextures(BYVAL n AS LONG,textures AS _UNSIGNED LONG)
SUB glGetBooleanv(BYVAL pname AS _UNSIGNED LONG,params AS _UNSIGNED _BYTE)
SUB glGetClipPlane(BYVAL plane AS _UNSIGNED LONG,equation AS DOUBLE)
SUB glGetDoublev(BYVAL pname AS _UNSIGNED LONG,params AS DOUBLE)
FUNCTION glGetError~&()
SUB glGetFloatv(BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glGetIntegerv(BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glGetLightfv(BYVAL light AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glGetLightiv(BYVAL light AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glGetMapdv(BYVAL target AS _UNSIGNED LONG,BYVAL query AS _UNSIGNED LONG,v AS DOUBLE)
SUB glGetMapfv(BYVAL target AS _UNSIGNED LONG,BYVAL query AS _UNSIGNED LONG,v AS SINGLE)
SUB glGetMapiv(BYVAL target AS _UNSIGNED LONG,BYVAL query AS _UNSIGNED LONG,v AS LONG)
SUB glGetMaterialfv(BYVAL face AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glGetMaterialiv(BYVAL face AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glGetPixelMapfv(BYVAL map AS _UNSIGNED LONG,values AS SINGLE)
SUB glGetPixelMapuiv(BYVAL map AS _UNSIGNED LONG,values AS _UNSIGNED LONG)
SUB glGetPixelMapusv(BYVAL map AS _UNSIGNED LONG,values AS _UNSIGNED INTEGER)
SUB glGetPointerv(BYVAL pname AS _UNSIGNED LONG,params AS _OFFSET)
SUB glGetPolygonStipple(mask AS _UNSIGNED _BYTE)
FUNCTION glGetString&&(BYVAL name AS _UNSIGNED LONG)
SUB glGetTexEnvfv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glGetTexEnviv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glGetTexGendv(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS DOUBLE)
SUB glGetTexGenfv(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glGetTexGeniv(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glGetTexImage(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL format AS _UNSIGNED LONG,BYVAL type AS _UNSIGNED LONG,pixels AS _OFFSET)
SUB glGetTexLevelParameterfv(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glGetTexLevelParameteriv(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glGetTexParameterfv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glGetTexParameteriv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glHint(BYVAL target AS _UNSIGNED LONG,BYVAL mode AS _UNSIGNED LONG)
SUB glIndexMask(BYVAL mask AS _UNSIGNED LONG)
SUB glIndexPointer(BYVAL type AS _UNSIGNED LONG,BYVAL stride AS LONG,pointer AS _OFFSET)
SUB glIndexd(BYVAL c AS DOUBLE)
SUB glIndexdv(c AS DOUBLE)
SUB glIndexf(BYVAL c AS SINGLE)
SUB glIndexfv(c AS SINGLE)
SUB glIndexi(BYVAL c AS LONG)
SUB glIndexiv(c AS LONG)
SUB glIndexs(BYVAL c AS INTEGER)
SUB glIndexsv(c AS INTEGER)
SUB glIndexub(BYVAL c AS _UNSIGNED _BYTE)
SUB glIndexubv(c AS _UNSIGNED _BYTE)
SUB glInitNames()
SUB glInterleavedArrays(BYVAL format AS _UNSIGNED LONG,BYVAL stride AS LONG,pointer AS _OFFSET)
FUNCTION glIsEnabled~%%(BYVAL cap AS _UNSIGNED LONG)
FUNCTION glIsList~%%(BYVAL list AS _UNSIGNED LONG)
FUNCTION glIsTexture~%%(BYVAL texture AS _UNSIGNED LONG)
SUB glLightModelf(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glLightModelfv(BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glLightModeli(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glLightModeliv(BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glLightf(BYVAL light AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glLightfv(BYVAL light AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glLighti(BYVAL light AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glLightiv(BYVAL light AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glLineStipple(BYVAL factor AS LONG,BYVAL pattern AS _UNSIGNED INTEGER)
SUB glLineWidth(BYVAL width AS SINGLE)
SUB glListBase(BYVAL base AS _UNSIGNED LONG)
SUB glLoadIdentity()
SUB glLoadMatrixd(m AS DOUBLE)
SUB glLoadMatrixf(m AS SINGLE)
SUB glLoadName(BYVAL name AS _UNSIGNED LONG)
SUB glLogicOp(BYVAL opcode AS _UNSIGNED LONG)
SUB glMap1d(BYVAL target AS _UNSIGNED LONG,BYVAL u1 AS DOUBLE,BYVAL u2 AS DOUBLE,BYVAL stride AS LONG,BYVAL order AS LONG,points AS DOUBLE)
SUB glMap1f(BYVAL target AS _UNSIGNED LONG,BYVAL u1 AS SINGLE,BYVAL u2 AS SINGLE,BYVAL stride AS LONG,BYVAL order AS LONG,points AS SINGLE)
SUB glMap2d(BYVAL target AS _UNSIGNED LONG,BYVAL u1 AS DOUBLE,BYVAL u2 AS DOUBLE,BYVAL ustride AS LONG,BYVAL uorder AS LONG,BYVAL v1 AS DOUBLE,BYVAL v2 AS DOUBLE,BYVAL vstride AS LONG,BYVAL vorder AS LONG,points AS DOUBLE)
SUB glMap2f(BYVAL target AS _UNSIGNED LONG,BYVAL u1 AS SINGLE,BYVAL u2 AS SINGLE,BYVAL ustride AS LONG,BYVAL uorder AS LONG,BYVAL v1 AS SINGLE,BYVAL v2 AS SINGLE,BYVAL vstride AS LONG,BYVAL vorder AS LONG,points AS SINGLE)
SUB glMapGrid1d(BYVAL un AS LONG,BYVAL u1 AS DOUBLE,BYVAL u2 AS DOUBLE)
SUB glMapGrid1f(BYVAL un AS LONG,BYVAL u1 AS SINGLE,BYVAL u2 AS SINGLE)
SUB glMapGrid2d(BYVAL un AS LONG,BYVAL u1 AS DOUBLE,BYVAL u2 AS DOUBLE,BYVAL vn AS LONG,BYVAL v1 AS DOUBLE,BYVAL v2 AS DOUBLE)
SUB glMapGrid2f(BYVAL un AS LONG,BYVAL u1 AS SINGLE,BYVAL u2 AS SINGLE,BYVAL vn AS LONG,BYVAL v1 AS SINGLE,BYVAL v2 AS SINGLE)
SUB glMaterialf(BYVAL face AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glMaterialfv(BYVAL face AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glMateriali(BYVAL face AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glMaterialiv(BYVAL face AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glMatrixMode(BYVAL mode AS _UNSIGNED LONG)
SUB glMultMatrixd(m AS DOUBLE)
SUB glMultMatrixf(m AS SINGLE)
SUB glNewList(BYVAL list AS _UNSIGNED LONG,BYVAL mode AS _UNSIGNED LONG)
SUB glNormal3b(BYVAL nx AS _BYTE,BYVAL ny AS _BYTE,BYVAL nz AS _BYTE)
SUB glNormal3bv(v AS _BYTE)
SUB glNormal3d(BYVAL nx AS DOUBLE,BYVAL ny AS DOUBLE,BYVAL nz AS DOUBLE)
SUB glNormal3dv(v AS DOUBLE)
SUB glNormal3f(BYVAL nx AS SINGLE,BYVAL ny AS SINGLE,BYVAL nz AS SINGLE)
SUB glNormal3fv(v AS SINGLE)
SUB glNormal3i(BYVAL nx AS LONG,BYVAL ny AS LONG,BYVAL nz AS LONG)
SUB glNormal3iv(v AS LONG)
SUB glNormal3s(BYVAL nx AS INTEGER,BYVAL ny AS INTEGER,BYVAL nz AS INTEGER)
SUB glNormal3sv(v AS INTEGER)
SUB glNormalPointer(BYVAL type AS _UNSIGNED LONG,BYVAL stride AS LONG,pointer AS _OFFSET)
SUB glOrtho(BYVAL left AS DOUBLE,BYVAL right AS DOUBLE,BYVAL bottom AS DOUBLE,BYVAL top AS DOUBLE,BYVAL zNear AS DOUBLE,BYVAL zFar AS DOUBLE)
SUB glPassThrough(BYVAL token AS SINGLE)
SUB glPixelMapfv(BYVAL map AS _UNSIGNED LONG,BYVAL mapsize AS LONG,values AS SINGLE)
SUB glPixelMapuiv(BYVAL map AS _UNSIGNED LONG,BYVAL mapsize AS LONG,values AS _UNSIGNED LONG)
SUB glPixelMapusv(BYVAL map AS _UNSIGNED LONG,BYVAL mapsize AS LONG,values AS _UNSIGNED INTEGER)
SUB glPixelStoref(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glPixelStorei(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glPixelTransferf(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glPixelTransferi(BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glPixelZoom(BYVAL xfactor AS SINGLE,BYVAL yfactor AS SINGLE)
SUB glPointSize(BYVAL size AS SINGLE)
SUB glPolygonMode(BYVAL face AS _UNSIGNED LONG,BYVAL mode AS _UNSIGNED LONG)
SUB glPolygonOffset(BYVAL factor AS SINGLE,BYVAL units AS SINGLE)
SUB glPolygonStipple(mask AS _UNSIGNED _BYTE)
SUB glPopAttrib()
SUB glPopClientAttrib()
SUB glPopMatrix()
SUB glPopName()
SUB glPrioritizeTextures(BYVAL n AS LONG,textures AS _UNSIGNED LONG,priorities AS SINGLE)
SUB glPushAttrib(BYVAL mask AS _UNSIGNED LONG)
SUB glPushClientAttrib(BYVAL mask AS _UNSIGNED LONG)
SUB glPushMatrix()
SUB glPushName(BYVAL name AS _UNSIGNED LONG)
SUB glRasterPos2d(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE)
SUB glRasterPos2dv(v AS DOUBLE)
SUB glRasterPos2f(BYVAL x AS SINGLE,BYVAL y AS SINGLE)
SUB glRasterPos2fv(v AS SINGLE)
SUB glRasterPos2i(BYVAL x AS LONG,BYVAL y AS LONG)
SUB glRasterPos2iv(v AS LONG)
SUB glRasterPos2s(BYVAL x AS INTEGER,BYVAL y AS INTEGER)
SUB glRasterPos2sv(v AS INTEGER)
SUB glRasterPos3d(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE,BYVAL z AS DOUBLE)
SUB glRasterPos3dv(v AS DOUBLE)
SUB glRasterPos3f(BYVAL x AS SINGLE,BYVAL y AS SINGLE,BYVAL z AS SINGLE)
SUB glRasterPos3fv(v AS SINGLE)
SUB glRasterPos3i(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL z AS LONG)
SUB glRasterPos3iv(v AS LONG)
SUB glRasterPos3s(BYVAL x AS INTEGER,BYVAL y AS INTEGER,BYVAL z AS INTEGER)
SUB glRasterPos3sv(v AS INTEGER)
SUB glRasterPos4d(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE,BYVAL z AS DOUBLE,BYVAL w AS DOUBLE)
SUB glRasterPos4dv(v AS DOUBLE)
SUB glRasterPos4f(BYVAL x AS SINGLE,BYVAL y AS SINGLE,BYVAL z AS SINGLE,BYVAL w AS SINGLE)
SUB glRasterPos4fv(v AS SINGLE)
SUB glRasterPos4i(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL z AS LONG,BYVAL w AS LONG)
SUB glRasterPos4iv(v AS LONG)
SUB glRasterPos4s(BYVAL x AS INTEGER,BYVAL y AS INTEGER,BYVAL z AS INTEGER,BYVAL w AS INTEGER)
SUB glRasterPos4sv(v AS INTEGER)
SUB glReadBuffer(BYVAL mode AS _UNSIGNED LONG)
SUB glReadPixels(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG,BYVAL height AS LONG,BYVAL format AS _UNSIGNED LONG,BYVAL type AS _UNSIGNED LONG,pixels AS _OFFSET)
SUB glRectd(BYVAL x1 AS DOUBLE,BYVAL y1 AS DOUBLE,BYVAL x2 AS DOUBLE,BYVAL y2 AS DOUBLE)
SUB glRectdv(v1 AS DOUBLE,v2 AS DOUBLE)
SUB glRectf(BYVAL x1 AS SINGLE,BYVAL y1 AS SINGLE,BYVAL x2 AS SINGLE,BYVAL y2 AS SINGLE)
SUB glRectfv(v1 AS SINGLE,v2 AS SINGLE)
SUB glRecti(BYVAL x1 AS LONG,BYVAL y1 AS LONG,BYVAL x2 AS LONG,BYVAL y2 AS LONG)
SUB glRectiv(v1 AS LONG,v2 AS LONG)
SUB glRects(BYVAL x1 AS INTEGER,BYVAL y1 AS INTEGER,BYVAL x2 AS INTEGER,BYVAL y2 AS INTEGER)
SUB glRectsv(v1 AS INTEGER,v2 AS INTEGER)
FUNCTION glRenderMode&(BYVAL mode AS _UNSIGNED LONG)
SUB glRotated(BYVAL angle AS DOUBLE,BYVAL x AS DOUBLE,BYVAL y AS DOUBLE,BYVAL z AS DOUBLE)
SUB glRotatef(BYVAL angle AS SINGLE,BYVAL x AS SINGLE,BYVAL y AS SINGLE,BYVAL z AS SINGLE)
SUB glScaled(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE,BYVAL z AS DOUBLE)
SUB glScalef(BYVAL x AS SINGLE,BYVAL y AS SINGLE,BYVAL z AS SINGLE)
SUB glScissor(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG,BYVAL height AS LONG)
SUB glSelectBuffer(BYVAL size AS LONG,buffer AS _UNSIGNED LONG)
SUB glShadeModel(BYVAL mode AS _UNSIGNED LONG)
SUB glStencilFunc(BYVAL func AS _UNSIGNED LONG,BYVAL ref AS LONG,BYVAL mask AS _UNSIGNED LONG)
SUB glStencilMask(BYVAL mask AS _UNSIGNED LONG)
SUB glStencilOp(BYVAL fail AS _UNSIGNED LONG,BYVAL zfail AS _UNSIGNED LONG,BYVAL zpass AS _UNSIGNED LONG)
SUB glTexCoord1d(BYVAL s AS DOUBLE)
SUB glTexCoord1dv(v AS DOUBLE)
SUB glTexCoord1f(BYVAL s AS SINGLE)
SUB glTexCoord1fv(v AS SINGLE)
SUB glTexCoord1i(BYVAL s AS LONG)
SUB glTexCoord1iv(v AS LONG)
SUB glTexCoord1s(BYVAL s AS INTEGER)
SUB glTexCoord1sv(v AS INTEGER)
SUB glTexCoord2d(BYVAL s AS DOUBLE,BYVAL t AS DOUBLE)
SUB glTexCoord2dv(v AS DOUBLE)
SUB glTexCoord2f(BYVAL s AS SINGLE,BYVAL t AS SINGLE)
SUB glTexCoord2fv(v AS SINGLE)
SUB glTexCoord2i(BYVAL s AS LONG,BYVAL t AS LONG)
SUB glTexCoord2iv(v AS LONG)
SUB glTexCoord2s(BYVAL s AS INTEGER,BYVAL t AS INTEGER)
SUB glTexCoord2sv(v AS INTEGER)
SUB glTexCoord3d(BYVAL s AS DOUBLE,BYVAL t AS DOUBLE,BYVAL r AS DOUBLE)
SUB glTexCoord3dv(v AS DOUBLE)
SUB glTexCoord3f(BYVAL s AS SINGLE,BYVAL t AS SINGLE,BYVAL r AS SINGLE)
SUB glTexCoord3fv(v AS SINGLE)
SUB glTexCoord3i(BYVAL s AS LONG,BYVAL t AS LONG,BYVAL r AS LONG)
SUB glTexCoord3iv(v AS LONG)
SUB glTexCoord3s(BYVAL s AS INTEGER,BYVAL t AS INTEGER,BYVAL r AS INTEGER)
SUB glTexCoord3sv(v AS INTEGER)
SUB glTexCoord4d(BYVAL s AS DOUBLE,BYVAL t AS DOUBLE,BYVAL r AS DOUBLE,BYVAL q AS DOUBLE)
SUB glTexCoord4dv(v AS DOUBLE)
SUB glTexCoord4f(BYVAL s AS SINGLE,BYVAL t AS SINGLE,BYVAL r AS SINGLE,BYVAL q AS SINGLE)
SUB glTexCoord4fv(v AS SINGLE)
SUB glTexCoord4i(BYVAL s AS LONG,BYVAL t AS LONG,BYVAL r AS LONG,BYVAL q AS LONG)
SUB glTexCoord4iv(v AS LONG)
SUB glTexCoord4s(BYVAL s AS INTEGER,BYVAL t AS INTEGER,BYVAL r AS INTEGER,BYVAL q AS INTEGER)
SUB glTexCoord4sv(v AS INTEGER)
SUB glTexCoordPointer(BYVAL size AS LONG,BYVAL type AS _UNSIGNED LONG,BYVAL stride AS LONG,pointer AS _OFFSET)
SUB glTexEnvf(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glTexEnvfv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glTexEnvi(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glTexEnviv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glTexGend(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS DOUBLE)
SUB glTexGendv(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS DOUBLE)
SUB glTexGenf(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glTexGenfv(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glTexGeni(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glTexGeniv(BYVAL coord AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glTexImage1D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL internalformat AS LONG,BYVAL width AS LONG,BYVAL border AS LONG,BYVAL format AS _UNSIGNED LONG,BYVAL type AS _UNSIGNED LONG,pixels AS _OFFSET)
SUB glTexImage2D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL internalformat AS LONG,BYVAL width AS LONG,BYVAL height AS LONG,BYVAL border AS LONG,BYVAL format AS _UNSIGNED LONG,BYVAL type AS _UNSIGNED LONG,pixels AS _OFFSET)
SUB glTexParameterf(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS SINGLE)
SUB glTexParameterfv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS SINGLE)
SUB glTexParameteri(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,BYVAL param AS LONG)
SUB glTexParameteriv(BYVAL target AS _UNSIGNED LONG,BYVAL pname AS _UNSIGNED LONG,params AS LONG)
SUB glTexSubImage1D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL xoffset AS LONG,BYVAL width AS LONG,BYVAL format AS _UNSIGNED LONG,BYVAL type AS _UNSIGNED LONG,pixels AS _OFFSET)
SUB glTexSubImage2D(BYVAL target AS _UNSIGNED LONG,BYVAL level AS LONG,BYVAL xoffset AS LONG,BYVAL yoffset AS LONG,BYVAL width AS LONG,BYVAL height AS LONG,BYVAL format AS _UNSIGNED LONG,BYVAL type AS _UNSIGNED LONG,pixels AS _OFFSET)
SUB glTranslated(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE,BYVAL z AS DOUBLE)
SUB glTranslatef(BYVAL x AS SINGLE,BYVAL y AS SINGLE,BYVAL z AS SINGLE)
SUB glVertex2d(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE)
SUB glVertex2dv(v AS DOUBLE)
SUB glVertex2f(BYVAL x AS SINGLE,BYVAL y AS SINGLE)
SUB glVertex2fv(v AS SINGLE)
SUB glVertex2i(BYVAL x AS LONG,BYVAL y AS LONG)
SUB glVertex2iv(v AS LONG)
SUB glVertex2s(BYVAL x AS INTEGER,BYVAL y AS INTEGER)
SUB glVertex2sv(v AS INTEGER)
SUB glVertex3d(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE,BYVAL z AS DOUBLE)
SUB glVertex3dv(v AS DOUBLE)
SUB glVertex3f(BYVAL x AS SINGLE,BYVAL y AS SINGLE,BYVAL z AS SINGLE)
SUB glVertex3fv(v AS SINGLE)
SUB glVertex3i(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL z AS LONG)
SUB glVertex3iv(v AS LONG)
SUB glVertex3s(BYVAL x AS INTEGER,BYVAL y AS INTEGER,BYVAL z AS INTEGER)
SUB glVertex3sv(v AS INTEGER)
SUB glVertex4d(BYVAL x AS DOUBLE,BYVAL y AS DOUBLE,BYVAL z AS DOUBLE,BYVAL w AS DOUBLE)
SUB glVertex4dv(v AS DOUBLE)
SUB glVertex4f(BYVAL x AS SINGLE,BYVAL y AS SINGLE,BYVAL z AS SINGLE,BYVAL w AS SINGLE)
SUB glVertex4fv(v AS SINGLE)
SUB glVertex4i(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL z AS LONG,BYVAL w AS LONG)
SUB glVertex4iv(v AS LONG)
SUB glVertex4s(BYVAL x AS INTEGER,BYVAL y AS INTEGER,BYVAL z AS INTEGER,BYVAL w AS INTEGER)
SUB glVertex4sv(v AS INTEGER)
SUB glVertexPointer(BYVAL size AS LONG,BYVAL type AS _UNSIGNED LONG,BYVAL stride AS LONG,pointer AS _OFFSET)
SUB glViewport(BYVAL x AS LONG,BYVAL y AS LONG,BYVAL width AS LONG,BYVAL height AS LONG)
END DECLARE
CONST GL_VERSION_1_1= 1 
CONST GL_ACCUM= 256 
CONST GL_LOAD= 257 
CONST GL_RETURN= 258 
CONST GL_MULT= 259 
CONST GL_ADD= 260 
CONST GL_NEVER= 512 
CONST GL_LESS= 513 
CONST GL_EQUAL= 514 
CONST GL_LEQUAL= 515 
CONST GL_GREATER= 516 
CONST GL_NOTEQUAL= 517 
CONST GL_GEQUAL= 518 
CONST GL_ALWAYS= 519 
CONST GL_CURRENT_BIT= 1 
CONST GL_POINT_BIT= 2 
CONST GL_LINE_BIT= 4 
CONST GL_POLYGON_BIT= 8 
CONST GL_POLYGON_STIPPLE_BIT= 16 
CONST GL_PIXEL_MODE_BIT= 32 
CONST GL_LIGHTING_BIT= 64 
CONST GL_FOG_BIT= 128 
CONST GL_DEPTH_BUFFER_BIT= 256 
CONST GL_ACCUM_BUFFER_BIT= 512 
CONST GL_STENCIL_BUFFER_BIT= 1024 
CONST GL_VIEWPORT_BIT= 2048 
CONST GL_TRANSFORM_BIT= 4096 
CONST GL_ENABLE_BIT= 8192 
CONST GL_COLOR_BUFFER_BIT= 16384 
CONST GL_HINT_BIT= 32768 
CONST GL_EVAL_BIT= 65536 
CONST GL_LIST_BIT= 131072 
CONST GL_TEXTURE_BIT= 262144 
CONST GL_SCISSOR_BIT= 524288 
CONST GL_ALL_ATTRIB_BITS= 1048575 
CONST GL_POINTS= 0 
CONST GL_LINES= 1 
CONST GL_LINE_LOOP= 2 
CONST GL_LINE_STRIP= 3 
CONST GL_TRIANGLES= 4 
CONST GL_TRIANGLE_STRIP= 5 
CONST GL_TRIANGLE_FAN= 6 
CONST GL_QUADS= 7 
CONST GL_QUAD_STRIP= 8 
CONST GL_POLYGON= 9 
CONST GL_ZERO= 0 
CONST GL_ONE= 1 
CONST GL_SRC_COLOR= 768 
CONST GL_ONE_MINUS_SRC_COLOR= 769 
CONST GL_SRC_ALPHA= 770 
CONST GL_ONE_MINUS_SRC_ALPHA= 771 
CONST GL_DST_ALPHA= 772 
CONST GL_ONE_MINUS_DST_ALPHA= 773 
CONST GL_DST_COLOR= 774 
CONST GL_ONE_MINUS_DST_COLOR= 775 
CONST GL_SRC_ALPHA_SATURATE= 776 
CONST GL_TRUE= 1 
CONST GL_FALSE= 0 
CONST GL_CLIP_PLANE0= 12288 
CONST GL_CLIP_PLANE1= 12289 
CONST GL_CLIP_PLANE2= 12290 
CONST GL_CLIP_PLANE3= 12291 
CONST GL_CLIP_PLANE4= 12292 
CONST GL_CLIP_PLANE5= 12293 
CONST GL_BYTE= 5120 
CONST GL_UNSIGNED_BYTE= 5121 
CONST GL_SHORT= 5122 
CONST GL_UNSIGNED_SHORT= 5123 
CONST GL_INT= 5124 
CONST GL_UNSIGNED_INT= 5125 
CONST GL_FLOAT= 5126 
CONST GL_2_BYTES= 5127 
CONST GL_3_BYTES= 5128 
CONST GL_4_BYTES= 5129 
CONST GL_DOUBLE= 5130 
CONST GL_NONE= 0 
CONST GL_FRONT_LEFT= 1024 
CONST GL_FRONT_RIGHT= 1025 
CONST GL_BACK_LEFT= 1026 
CONST GL_BACK_RIGHT= 1027 
CONST GL_FRONT= 1028 
CONST GL_BACK= 1029 
CONST GL_LEFT= 1030 
CONST GL_RIGHT= 1031 
CONST GL_FRONT_AND_BACK= 1032 
CONST GL_AUX0= 1033 
CONST GL_AUX1= 1034 
CONST GL_AUX2= 1035 
CONST GL_AUX3= 1036 
CONST GL_NO_ERROR= 0 
CONST GL_INVALID_ENUM= 1280 
CONST GL_INVALID_VALUE= 1281 
CONST GL_INVALID_OPERATION= 1282 
CONST GL_STACK_OVERFLOW= 1283 
CONST GL_STACK_UNDERFLOW= 1284 
CONST GL_OUT_OF_MEMORY= 1285 
CONST GL_2D= 1536 
CONST GL_3D= 1537 
CONST GL_3D_COLOR= 1538 
CONST GL_3D_COLOR_TEXTURE= 1539 
CONST GL_4D_COLOR_TEXTURE= 1540 
CONST GL_PASS_THROUGH_TOKEN= 1792 
CONST GL_POINT_TOKEN= 1793 
CONST GL_LINE_TOKEN= 1794 
CONST GL_POLYGON_TOKEN= 1795 
CONST GL_BITMAP_TOKEN= 1796 
CONST GL_DRAW_PIXEL_TOKEN= 1797 
CONST GL_COPY_PIXEL_TOKEN= 1798 
CONST GL_LINE_RESET_TOKEN= 1799 
CONST GL_EXP= 2048 
CONST GL_EXP2= 2049 
CONST GL_CW= 2304 
CONST GL_CCW= 2305 
CONST GL_COEFF= 2560 
CONST GL_ORDER= 2561 
CONST GL_DOMAIN= 2562 
CONST GL_CURRENT_COLOR= 2816 
CONST GL_CURRENT_INDEX= 2817 
CONST GL_CURRENT_NORMAL= 2818 
CONST GL_CURRENT_TEXTURE_COORDS= 2819 
CONST GL_CURRENT_RASTER_COLOR= 2820 
CONST GL_CURRENT_RASTER_INDEX= 2821 
CONST GL_CURRENT_RASTER_TEXTURE_COORDS= 2822 
CONST GL_CURRENT_RASTER_POSITION= 2823 
CONST GL_CURRENT_RASTER_POSITION_VALID= 2824 
CONST GL_CURRENT_RASTER_DISTANCE= 2825 
CONST GL_POINT_SMOOTH= 2832 
CONST GL_POINT_SIZE= 2833 
CONST GL_POINT_SIZE_RANGE= 2834 
CONST GL_POINT_SIZE_GRANULARITY= 2835 
CONST GL_LINE_SMOOTH= 2848 
CONST GL_LINE_WIDTH= 2849 
CONST GL_LINE_WIDTH_RANGE= 2850 
CONST GL_LINE_WIDTH_GRANULARITY= 2851 
CONST GL_LINE_STIPPLE= 2852 
CONST GL_LINE_STIPPLE_PATTERN= 2853 
CONST GL_LINE_STIPPLE_REPEAT= 2854 
CONST GL_LIST_MODE= 2864 
CONST GL_MAX_LIST_NESTING= 2865 
CONST GL_LIST_BASE= 2866 
CONST GL_LIST_INDEX= 2867 
CONST GL_POLYGON_MODE= 2880 
CONST GL_POLYGON_SMOOTH= 2881 
CONST GL_POLYGON_STIPPLE= 2882 
CONST GL_EDGE_FLAG= 2883 
CONST GL_CULL_FACE= 2884 
CONST GL_CULL_FACE_MODE= 2885 
CONST GL_FRONT_FACE= 2886 
CONST GL_LIGHTING= 2896 
CONST GL_LIGHT_MODEL_LOCAL_VIEWER= 2897 
CONST GL_LIGHT_MODEL_TWO_SIDE= 2898 
CONST GL_LIGHT_MODEL_AMBIENT= 2899 
CONST GL_SHADE_MODEL= 2900 
CONST GL_COLOR_MATERIAL_FACE= 2901 
CONST GL_COLOR_MATERIAL_PARAMETER= 2902 
CONST GL_COLOR_MATERIAL= 2903 
CONST GL_FOG= 2912 
CONST GL_FOG_INDEX= 2913 
CONST GL_FOG_DENSITY= 2914 
CONST GL_FOG_START= 2915 
CONST GL_FOG_END= 2916 
CONST GL_FOG_MODE= 2917 
CONST GL_FOG_COLOR= 2918 
CONST GL_DEPTH_RANGE= 2928 
CONST GL_DEPTH_TEST= 2929 
CONST GL_DEPTH_WRITEMASK= 2930 
CONST GL_DEPTH_CLEAR_VALUE= 2931 
CONST GL_DEPTH_FUNC= 2932 
CONST GL_ACCUM_CLEAR_VALUE= 2944 
CONST GL_STENCIL_TEST= 2960 
CONST GL_STENCIL_CLEAR_VALUE= 2961 
CONST GL_STENCIL_FUNC= 2962 
CONST GL_STENCIL_VALUE_MASK= 2963 
CONST GL_STENCIL_FAIL= 2964 
CONST GL_STENCIL_PASS_DEPTH_FAIL= 2965 
CONST GL_STENCIL_PASS_DEPTH_PASS= 2966 
CONST GL_STENCIL_REF= 2967 
CONST GL_STENCIL_WRITEMASK= 2968 
CONST GL_MATRIX_MODE= 2976 
CONST GL_NORMALIZE= 2977 
CONST GL_VIEWPORT= 2978 
CONST GL_MODELVIEW_STACK_DEPTH= 2979 
CONST GL_PROJECTION_STACK_DEPTH= 2980 
CONST GL_TEXTURE_STACK_DEPTH= 2981 
CONST GL_MODELVIEW_MATRIX= 2982 
CONST GL_PROJECTION_MATRIX= 2983 
CONST GL_TEXTURE_MATRIX= 2984 
CONST GL_ATTRIB_STACK_DEPTH= 2992 
CONST GL_CLIENT_ATTRIB_STACK_DEPTH= 2993 
CONST GL_ALPHA_TEST= 3008 
CONST GL_ALPHA_TEST_FUNC= 3009 
CONST GL_ALPHA_TEST_REF= 3010 
CONST GL_DITHER= 3024 
CONST GL_BLEND_DST= 3040 
CONST GL_BLEND_SRC= 3041 
CONST GL_BLEND= 3042 
CONST GL_LOGIC_OP_MODE= 3056 
CONST GL_INDEX_LOGIC_OP= 3057 
CONST GL_COLOR_LOGIC_OP= 3058 
CONST GL_AUX_BUFFERS= 3072 
CONST GL_DRAW_BUFFER= 3073 
CONST GL_READ_BUFFER= 3074 
CONST GL_SCISSOR_BOX= 3088 
CONST GL_SCISSOR_TEST= 3089 
CONST GL_INDEX_CLEAR_VALUE= 3104 
CONST GL_INDEX_WRITEMASK= 3105 
CONST GL_COLOR_CLEAR_VALUE= 3106 
CONST GL_COLOR_WRITEMASK= 3107 
CONST GL_INDEX_MODE= 3120 
CONST GL_RGBA_MODE= 3121 
CONST GL_DOUBLEBUFFER= 3122 
CONST GL_STEREO= 3123 
CONST GL_RENDER_MODE= 3136 
CONST GL_PERSPECTIVE_CORRECTION_HINT= 3152 
CONST GL_POINT_SMOOTH_HINT= 3153 
CONST GL_LINE_SMOOTH_HINT= 3154 
CONST GL_POLYGON_SMOOTH_HINT= 3155 
CONST GL_FOG_HINT= 3156 
CONST GL_TEXTURE_GEN_S= 3168 
CONST GL_TEXTURE_GEN_T= 3169 
CONST GL_TEXTURE_GEN_R= 3170 
CONST GL_TEXTURE_GEN_Q= 3171 
CONST GL_PIXEL_MAP_I_TO_I= 3184 
CONST GL_PIXEL_MAP_S_TO_S= 3185 
CONST GL_PIXEL_MAP_I_TO_R= 3186 
CONST GL_PIXEL_MAP_I_TO_G= 3187 
CONST GL_PIXEL_MAP_I_TO_B= 3188 
CONST GL_PIXEL_MAP_I_TO_A= 3189 
CONST GL_PIXEL_MAP_R_TO_R= 3190 
CONST GL_PIXEL_MAP_G_TO_G= 3191 
CONST GL_PIXEL_MAP_B_TO_B= 3192 
CONST GL_PIXEL_MAP_A_TO_A= 3193 
CONST GL_PIXEL_MAP_I_TO_I_SIZE= 3248 
CONST GL_PIXEL_MAP_S_TO_S_SIZE= 3249 
CONST GL_PIXEL_MAP_I_TO_R_SIZE= 3250 
CONST GL_PIXEL_MAP_I_TO_G_SIZE= 3251 
CONST GL_PIXEL_MAP_I_TO_B_SIZE= 3252 
CONST GL_PIXEL_MAP_I_TO_A_SIZE= 3253 
CONST GL_PIXEL_MAP_R_TO_R_SIZE= 3254 
CONST GL_PIXEL_MAP_G_TO_G_SIZE= 3255 
CONST GL_PIXEL_MAP_B_TO_B_SIZE= 3256 
CONST GL_PIXEL_MAP_A_TO_A_SIZE= 3257 
CONST GL_UNPACK_SWAP_BYTES= 3312 
CONST GL_UNPACK_LSB_FIRST= 3313 
CONST GL_UNPACK_ROW_LENGTH= 3314 
CONST GL_UNPACK_SKIP_ROWS= 3315 
CONST GL_UNPACK_SKIP_PIXELS= 3316 
CONST GL_UNPACK_ALIGNMENT= 3317 
CONST GL_PACK_SWAP_BYTES= 3328 
CONST GL_PACK_LSB_FIRST= 3329 
CONST GL_PACK_ROW_LENGTH= 3330 
CONST GL_PACK_SKIP_ROWS= 3331 
CONST GL_PACK_SKIP_PIXELS= 3332 
CONST GL_PACK_ALIGNMENT= 3333 
CONST GL_MAP_COLOR= 3344 
CONST GL_MAP_STENCIL= 3345 
CONST GL_INDEX_SHIFT= 3346 
CONST GL_INDEX_OFFSET= 3347 
CONST GL_RED_SCALE= 3348 
CONST GL_RED_BIAS= 3349 
CONST GL_ZOOM_X= 3350 
CONST GL_ZOOM_Y= 3351 
CONST GL_GREEN_SCALE= 3352 
CONST GL_GREEN_BIAS= 3353 
CONST GL_BLUE_SCALE= 3354 
CONST GL_BLUE_BIAS= 3355 
CONST GL_ALPHA_SCALE= 3356 
CONST GL_ALPHA_BIAS= 3357 
CONST GL_DEPTH_SCALE= 3358 
CONST GL_DEPTH_BIAS= 3359 
CONST GL_MAX_EVAL_ORDER= 3376 
CONST GL_MAX_LIGHTS= 3377 
CONST GL_MAX_CLIP_PLANES= 3378 
CONST GL_MAX_TEXTURE_SIZE= 3379 
CONST GL_MAX_PIXEL_MAP_TABLE= 3380 
CONST GL_MAX_ATTRIB_STACK_DEPTH= 3381 
CONST GL_MAX_MODELVIEW_STACK_DEPTH= 3382 
CONST GL_MAX_NAME_STACK_DEPTH= 3383 
CONST GL_MAX_PROJECTION_STACK_DEPTH= 3384 
CONST GL_MAX_TEXTURE_STACK_DEPTH= 3385 
CONST GL_MAX_VIEWPORT_DIMS= 3386 
CONST GL_MAX_CLIENT_ATTRIB_STACK_DEPTH= 3387 
CONST GL_SUBPIXEL_BITS= 3408 
CONST GL_INDEX_BITS= 3409 
CONST GL_RED_BITS= 3410 
CONST GL_GREEN_BITS= 3411 
CONST GL_BLUE_BITS= 3412 
CONST GL_ALPHA_BITS= 3413 
CONST GL_DEPTH_BITS= 3414 
CONST GL_STENCIL_BITS= 3415 
CONST GL_ACCUM_RED_BITS= 3416 
CONST GL_ACCUM_GREEN_BITS= 3417 
CONST GL_ACCUM_BLUE_BITS= 3418 
CONST GL_ACCUM_ALPHA_BITS= 3419 
CONST GL_NAME_STACK_DEPTH= 3440 
CONST GL_AUTO_NORMAL= 3456 
CONST GL_MAP1_COLOR_4= 3472 
CONST GL_MAP1_INDEX= 3473 
CONST GL_MAP1_NORMAL= 3474 
CONST GL_MAP1_TEXTURE_COORD_1= 3475 
CONST GL_MAP1_TEXTURE_COORD_2= 3476 
CONST GL_MAP1_TEXTURE_COORD_3= 3477 
CONST GL_MAP1_TEXTURE_COORD_4= 3478 
CONST GL_MAP1_VERTEX_3= 3479 
CONST GL_MAP1_VERTEX_4= 3480 
CONST GL_MAP2_COLOR_4= 3504 
CONST GL_MAP2_INDEX= 3505 
CONST GL_MAP2_NORMAL= 3506 
CONST GL_MAP2_TEXTURE_COORD_1= 3507 
CONST GL_MAP2_TEXTURE_COORD_2= 3508 
CONST GL_MAP2_TEXTURE_COORD_3= 3509 
CONST GL_MAP2_TEXTURE_COORD_4= 3510 
CONST GL_MAP2_VERTEX_3= 3511 
CONST GL_MAP2_VERTEX_4= 3512 
CONST GL_MAP1_GRID_DOMAIN= 3536 
CONST GL_MAP1_GRID_SEGMENTS= 3537 
CONST GL_MAP2_GRID_DOMAIN= 3538 
CONST GL_MAP2_GRID_SEGMENTS= 3539 
CONST GL_TEXTURE_1D= 3552 
CONST GL_TEXTURE_2D= 3553 
CONST GL_FEEDBACK_BUFFER_POINTER= 3568 
CONST GL_FEEDBACK_BUFFER_SIZE= 3569 
CONST GL_FEEDBACK_BUFFER_TYPE= 3570 
CONST GL_SELECTION_BUFFER_POINTER= 3571 
CONST GL_SELECTION_BUFFER_SIZE= 3572 
CONST GL_TEXTURE_WIDTH= 4096 
CONST GL_TEXTURE_HEIGHT= 4097 
CONST GL_TEXTURE_INTERNAL_FORMAT= 4099 
CONST GL_TEXTURE_BORDER_COLOR= 4100 
CONST GL_TEXTURE_BORDER= 4101 
CONST GL_DONT_CARE= 4352 
CONST GL_FASTEST= 4353 
CONST GL_NICEST= 4354 
CONST GL_LIGHT0= 16384 
CONST GL_LIGHT1= 16385 
CONST GL_LIGHT2= 16386 
CONST GL_LIGHT3= 16387 
CONST GL_LIGHT4= 16388 
CONST GL_LIGHT5= 16389 
CONST GL_LIGHT6= 16390 
CONST GL_LIGHT7= 16391 
CONST GL_AMBIENT= 4608 
CONST GL_DIFFUSE= 4609 
CONST GL_SPECULAR= 4610 
CONST GL_POSITION= 4611 
CONST GL_SPOT_DIRECTION= 4612 
CONST GL_SPOT_EXPONENT= 4613 
CONST GL_SPOT_CUTOFF= 4614 
CONST GL_CONSTANT_ATTENUATION= 4615 
CONST GL_LINEAR_ATTENUATION= 4616 
CONST GL_QUADRATIC_ATTENUATION= 4617 
CONST GL_COMPILE= 4864 
CONST GL_COMPILE_AND_EXECUTE= 4865 
CONST GL_CLEAR= 5376 
CONST GL_AND= 5377 
CONST GL_AND_REVERSE= 5378 
CONST GL_COPY= 5379 
CONST GL_AND_INVERTED= 5380 
CONST GL_NOOP= 5381 
CONST GL_XOR= 5382 
CONST GL_OR= 5383 
CONST GL_NOR= 5384 
CONST GL_EQUIV= 5385 
CONST GL_INVERT= 5386 
CONST GL_OR_REVERSE= 5387 
CONST GL_COPY_INVERTED= 5388 
CONST GL_OR_INVERTED= 5389 
CONST GL_NAND= 5390 
CONST GL_SET= 5391 
CONST GL_EMISSION= 5632 
CONST GL_SHININESS= 5633 
CONST GL_AMBIENT_AND_DIFFUSE= 5634 
CONST GL_COLOR_INDEXES= 5635 
CONST GL_MODELVIEW= 5888 
CONST GL_PROJECTION= 5889 
CONST GL_TEXTURE= 5890 
CONST GL_COLOR= 6144 
CONST GL_DEPTH= 6145 
CONST GL_STENCIL= 6146 
CONST GL_COLOR_INDEX= 6400 
CONST GL_STENCIL_INDEX= 6401 
CONST GL_DEPTH_COMPONENT= 6402 
CONST GL_RED= 6403 
CONST GL_GREEN= 6404 
CONST GL_BLUE= 6405 
CONST GL_ALPHA= 6406 
CONST GL_RGB= 6407 
CONST GL_RGBA= 6408 
CONST GL_LUMINANCE= 6409 
CONST GL_LUMINANCE_ALPHA= 6410 
CONST GL_BITMAP= 6656 
CONST GL_POINT= 6912 
CONST GL_LINE= 6913 
CONST GL_FILL= 6914 
CONST GL_RENDER= 7168 
CONST GL_FEEDBACK= 7169 
CONST GL_SELECT= 7170 
CONST GL_FLAT= 7424 
CONST GL_SMOOTH= 7425 
CONST GL_KEEP= 7680 
CONST GL_REPLACE= 7681 
CONST GL_INCR= 7682 
CONST GL_DECR= 7683 
CONST GL_VENDOR= 7936 
CONST GL_RENDERER= 7937 
CONST GL_VERSION= 7938 
CONST GL_EXTENSIONS= 7939 
CONST GL_S= 8192 
CONST GL_T= 8193 
CONST GL_R= 8194 
CONST GL_Q= 8195 
CONST GL_MODULATE= 8448 
CONST GL_DECAL= 8449 
CONST GL_TEXTURE_ENV_MODE= 8704 
CONST GL_TEXTURE_ENV_COLOR= 8705 
CONST GL_TEXTURE_ENV= 8960 
CONST GL_EYE_LINEAR= 9216 
CONST GL_OBJECT_LINEAR= 9217 
CONST GL_SPHERE_MAP= 9218 
CONST GL_TEXTURE_GEN_MODE= 9472 
CONST GL_OBJECT_PLANE= 9473 
CONST GL_EYE_PLANE= 9474 
CONST GL_NEAREST= 9728 
CONST GL_LINEAR= 9729 
CONST GL_NEAREST_MIPMAP_NEAREST= 9984 
CONST GL_LINEAR_MIPMAP_NEAREST= 9985 
CONST GL_NEAREST_MIPMAP_LINEAR= 9986 
CONST GL_LINEAR_MIPMAP_LINEAR= 9987 
CONST GL_TEXTURE_MAG_FILTER= 10240 
CONST GL_TEXTURE_MIN_FILTER= 10241 
CONST GL_TEXTURE_WRAP_S= 10242 
CONST GL_TEXTURE_WRAP_T= 10243 
CONST GL_CLAMP= 10496 
CONST GL_REPEAT= 10497 
CONST GL_CLIENT_PIXEL_STORE_BIT= 1 
CONST GL_CLIENT_VERTEX_ARRAY_BIT= 2 
CONST GL_CLIENT_ALL_ATTRIB_BITS= 4294967295 
CONST GL_POLYGON_OFFSET_FACTOR= 32824 
CONST GL_POLYGON_OFFSET_UNITS= 10752 
CONST GL_POLYGON_OFFSET_POINT= 10753 
CONST GL_POLYGON_OFFSET_LINE= 10754 
CONST GL_POLYGON_OFFSET_FILL= 32823 
CONST GL_ALPHA4= 32827 
CONST GL_ALPHA8= 32828 
CONST GL_ALPHA12= 32829 
CONST GL_ALPHA16= 32830 
CONST GL_LUMINANCE4= 32831 
CONST GL_LUMINANCE8= 32832 
CONST GL_LUMINANCE12= 32833 
CONST GL_LUMINANCE16= 32834 
CONST GL_LUMINANCE4_ALPHA4= 32835 
CONST GL_LUMINANCE6_ALPHA2= 32836 
CONST GL_LUMINANCE8_ALPHA8= 32837 
CONST GL_LUMINANCE12_ALPHA4= 32838 
CONST GL_LUMINANCE12_ALPHA12= 32839 
CONST GL_LUMINANCE16_ALPHA16= 32840 
CONST GL_INTENSITY= 32841 
CONST GL_INTENSITY4= 32842 
CONST GL_INTENSITY8= 32843 
CONST GL_INTENSITY12= 32844 
CONST GL_INTENSITY16= 32845 
CONST GL_R3_G3_B2= 10768 
CONST GL_RGB4= 32847 
CONST GL_RGB5= 32848 
CONST GL_RGB8= 32849 
CONST GL_RGB10= 32850 
CONST GL_RGB12= 32851 
CONST GL_RGB16= 32852 
CONST GL_RGBA2= 32853 
CONST GL_RGBA4= 32854 
CONST GL_RGB5_A1= 32855 
CONST GL_RGBA8= 32856 
CONST GL_RGB10_A2= 32857 
CONST GL_RGBA12= 32858 
CONST GL_RGBA16= 32859 
CONST GL_TEXTURE_RED_SIZE= 32860 
CONST GL_TEXTURE_GREEN_SIZE= 32861 
CONST GL_TEXTURE_BLUE_SIZE= 32862 
CONST GL_TEXTURE_ALPHA_SIZE= 32863 
CONST GL_TEXTURE_LUMINANCE_SIZE= 32864 
CONST GL_TEXTURE_INTENSITY_SIZE= 32865 
CONST GL_PROXY_TEXTURE_1D= 32867 
CONST GL_PROXY_TEXTURE_2D= 32868 
CONST GL_TEXTURE_PRIORITY= 32870 
CONST GL_TEXTURE_RESIDENT= 32871 
CONST GL_TEXTURE_BINDING_1D= 32872 
CONST GL_TEXTURE_BINDING_2D= 32873 
CONST GL_VERTEX_ARRAY= 32884 
CONST GL_NORMAL_ARRAY= 32885 
CONST GL_COLOR_ARRAY= 32886 
CONST GL_INDEX_ARRAY= 32887 
CONST GL_TEXTURE_COORD_ARRAY= 32888 
CONST GL_EDGE_FLAG_ARRAY= 32889 
CONST GL_VERTEX_ARRAY_SIZE= 32890 
CONST GL_VERTEX_ARRAY_TYPE= 32891 
CONST GL_VERTEX_ARRAY_STRIDE= 32892 
CONST GL_NORMAL_ARRAY_TYPE= 32894 
CONST GL_NORMAL_ARRAY_STRIDE= 32895 
CONST GL_COLOR_ARRAY_SIZE= 32897 
CONST GL_COLOR_ARRAY_TYPE= 32898 
CONST GL_COLOR_ARRAY_STRIDE= 32899 
CONST GL_INDEX_ARRAY_TYPE= 32901 
CONST GL_INDEX_ARRAY_STRIDE= 32902 
CONST GL_TEXTURE_COORD_ARRAY_SIZE= 32904 
CONST GL_TEXTURE_COORD_ARRAY_TYPE= 32905 
CONST GL_TEXTURE_COORD_ARRAY_STRIDE= 32906 
CONST GL_EDGE_FLAG_ARRAY_STRIDE= 32908 
CONST GL_VERTEX_ARRAY_POINTER= 32910 
CONST GL_NORMAL_ARRAY_POINTER= 32911 
CONST GL_COLOR_ARRAY_POINTER= 32912 
CONST GL_INDEX_ARRAY_POINTER= 32913 
CONST GL_TEXTURE_COORD_ARRAY_POINTER= 32914 
CONST GL_EDGE_FLAG_ARRAY_POINTER= 32915 
CONST GL_V2F= 10784 
CONST GL_V3F= 10785 
CONST GL_C4UB_V2F= 10786 
CONST GL_C4UB_V3F= 10787 
CONST GL_C3F_V3F= 10788 
CONST GL_N3F_V3F= 10789 
CONST GL_C4F_N3F_V3F= 10790 
CONST GL_T2F_V3F= 10791 
CONST GL_T4F_V4F= 10792 
CONST GL_T2F_C4UB_V3F= 10793 
CONST GL_T2F_C3F_V3F= 10794 
CONST GL_T2F_N3F_V3F= 10795 
CONST GL_T2F_C4F_N3F_V3F= 10796 
CONST GL_T4F_C4F_N3F_V4F= 10797 
CONST GL_VERTEX_ARRAY_EXT= 32884 
CONST GL_NORMAL_ARRAY_EXT= 32885 
CONST GL_COLOR_ARRAY_EXT= 32886 
CONST GL_INDEX_ARRAY_EXT= 32887 
CONST GL_TEXTURE_COORD_ARRAY_EXT= 32888 
CONST GL_EDGE_FLAG_ARRAY_EXT= 32889 
CONST GL_VERTEX_ARRAY_SIZE_EXT= 32890 
CONST GL_VERTEX_ARRAY_TYPE_EXT= 32891 
CONST GL_VERTEX_ARRAY_STRIDE_EXT= 32892 
CONST GL_VERTEX_ARRAY_COUNT_EXT= 32893 
CONST GL_NORMAL_ARRAY_TYPE_EXT= 32894 
CONST GL_NORMAL_ARRAY_STRIDE_EXT= 32895 
CONST GL_NORMAL_ARRAY_COUNT_EXT= 32896 
CONST GL_COLOR_ARRAY_SIZE_EXT= 32897 
CONST GL_COLOR_ARRAY_TYPE_EXT= 32898 
CONST GL_COLOR_ARRAY_STRIDE_EXT= 32899 
CONST GL_COLOR_ARRAY_COUNT_EXT= 32900 
CONST GL_INDEX_ARRAY_TYPE_EXT= 32901 
CONST GL_INDEX_ARRAY_STRIDE_EXT= 32902 
CONST GL_INDEX_ARRAY_COUNT_EXT= 32903 
CONST GL_TEXTURE_COORD_ARRAY_SIZE_EXT= 32904 
CONST GL_TEXTURE_COORD_ARRAY_TYPE_EXT= 32905 
CONST GL_TEXTURE_COORD_ARRAY_STRIDE_EXT= 32906 
CONST GL_TEXTURE_COORD_ARRAY_COUNT_EXT= 32907 
CONST GL_EDGE_FLAG_ARRAY_STRIDE_EXT= 32908 
CONST GL_EDGE_FLAG_ARRAY_COUNT_EXT= 32909 
CONST GL_VERTEX_ARRAY_POINTER_EXT= 32910 
CONST GL_NORMAL_ARRAY_POINTER_EXT= 32911 
CONST GL_COLOR_ARRAY_POINTER_EXT= 32912 
CONST GL_INDEX_ARRAY_POINTER_EXT= 32913 
CONST GL_TEXTURE_COORD_ARRAY_POINTER_EXT= 32914 
CONST GL_EDGE_FLAG_ARRAY_POINTER_EXT= 32915 
CONST GL_DOUBLE_EXT= 5130 
CONST GL_BGR_EXT= 32992 
CONST GL_BGRA_EXT= 32993 
CONST GL_COLOR_TABLE_FORMAT_EXT= 32984 
CONST GL_COLOR_TABLE_WIDTH_EXT= 32985 
CONST GL_COLOR_TABLE_RED_SIZE_EXT= 32986 
CONST GL_COLOR_TABLE_GREEN_SIZE_EXT= 32987 
CONST GL_COLOR_TABLE_BLUE_SIZE_EXT= 32988 
CONST GL_COLOR_TABLE_ALPHA_SIZE_EXT= 32989 
CONST GL_COLOR_TABLE_LUMINANCE_SIZE_EXT= 32990 
CONST GL_COLOR_TABLE_INTENSITY_SIZE_EXT= 32991 
CONST GL_COLOR_INDEX1_EXT= 32994 
CONST GL_COLOR_INDEX2_EXT= 32995 
CONST GL_COLOR_INDEX4_EXT= 32996 
CONST GL_COLOR_INDEX8_EXT= 32997 
CONST GL_COLOR_INDEX12_EXT= 32998 
CONST GL_COLOR_INDEX16_EXT= 32999 
CONST GL_MAX_ELEMENTS_VERTICES_WIN= 33000 
CONST GL_MAX_ELEMENTS_INDICES_WIN= 33001 
CONST GL_PHONG_WIN= 33002 
CONST GL_PHONG_HINT_WIN= 33003 
CONST GL_FOG_SPECULAR_TEXTURE_WIN= 33004 
CONST GL_LOGIC_OP= 3057 
CONST GL_TEXTURE_COMPONENTS= 4099 
